### ISSUE TITLE
Run container as non root

### ISSUE THREAD

**Issue by Helmelt** [gocd/docker-gocd-agent-alpine-3.8#1]
##### Issue Type
* Bug Report

##### Summary
When launching the container with non root privileges the docker-entrypoint.sh script will not create the necessary directories for the agent to work properly. 

I changed the docker-entrypoint.sh and commented out the line "if [ "$(id -u)" = '0' ]; then" (line 66) and the closing fi of course and build my custom image and made it work that way.

Furthermore we deploy the agent with kubernetes and there I had to mount the /go and /godata directories.

`- name: go-storage
            mountPath: /go
          - name: go-storage
            mountPath: /godata
      volumes:
        - name: go-storage
          emptyDir: {}
`

I don't know it this is intended behavior but since everything seems to work when not checking for root user and having mounted the necessary folders I guess this can easily be fixed.

**Comment by arvindsv** [comment]
@GaneshSPatil This looks to be related to what we were talking about last week. Can you take a look?

**Comment by Helmelt** [comment]
sure, I tried to find the issue you were talking about but a link would be nice

**Comment by arvindsv** [comment]
@Helmelt There isn't an open issue for it, but we were figuring out what changes are needed to make this work with OpenShift and saw that it doesn't like root containers.

/cc @GaneshSPatil - Ping.

**Comment by chadlwilson** [comment]
I believe this is done already some time ago, however if still relevant, please open an issue on https://github.com/gocd/gocd
